name = "Hjertnes"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "Hjertnes's hugo theme; based on blank"
homepage = "https://github.com/hjertnes/hugo-theme-hjertnes"
tags = ["blog",]
features = ["blog"]
min_version = 0.19

[author]
  name = "Hjertnes"
  homepage = "https://github.com/hjertnes"